# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'odoo-ai: AI Agent Core',
    'version': '18.0.1.137',
    'summary': 'AI Agent Core — Org-stomme, heartbeat, onboarding, task-system',
    'category': 'AI Orchestration',
    'description': """
        AI Agent Core — self-sufficient AI agent platform for Odoo.
        
        Now includes organization layer:
        * AI Organization Goals (OKR) — hierarchical with cascade
        * AI Tasks — persistent with atomic checkout, blockers, work products
        * Heartbeat system — proactive coworkers that wake and work
        * AI CEO Onboarding — scans modules, interviews CEO, creates org
        * AI Orchestration Dashboard — org chart with kanban, onboarding button
        * Bridge Protocol — connect strategy, marketing, helpdesk modules
        * hr integration — AI coworkers as hr.employees, AI department managers
    """,
    'author': 'Vertel AB',
    'website': 'https://vertel.se/apps/odoo-ai/ai_agent_core',
    'license': 'AGPL-3',
    # ai_agent (legacy) definierar samma modeller/xmlids (ai.tool,
    # view_ai_tool_*) och är inkompatibel. Odoo 18 läser inte denna nyckel,
    # men den dokumenterar avsikten; faktisk spärr = pre_init_hook.
    'conflicts': ['ai_agent'],
    'depends': [
        'base',
        'mail',
        'html_editor',
        'hr',
        'base_automation',
    ],
    'data': [
        'security/ai_groups.xml',
        'security/ir.model.access.csv',
        'security/ai_hitl_rules.xml',
        'views/ai_actions.xml',
        'data/okf_default_artifact_types.xml',
        'data/okf_artifact_types_personal.xml',
        'data/okf_access_resolvers.xml',
        'data/cron_personal_index.xml',
        'data/cron_okf_index_dirty.xml',
        'data/cron_okf_process_uploads.xml',
        'data/cron_company_memory_indexers.xml',
        'data/okf_migrate_legacy.xml',
        'data/skill_odoo_core.xml',
        'data/builtin_tools_seed.xml',
        'data/default_coworker.xml',
        'views/ai_artifact_type_views.xml',
        'views/ai_okf_concept_views.xml',
        'views/ai_access_resolver_views.xml',
        'views/ai_okf_dashboard_views.xml',
        'views/ai_okf_upload_views.xml',
        'data/memory_scopes.xml',
        'data/provider_openai.xml',
        'data/provider_anthropic.xml',
        'data/provider_deepseek.xml',
        'data/provider_google.xml',
        'data/provider_cerebras.xml',
        'data/provider_groq.xml',
        'data/provider_ollama.xml',
        'data/provider_openrouter.xml',
        'data/provider_bifrost.xml',
        'data/ensure_init_resources.xml',
        'data/cron_hitl.xml',
        'data/cron_mail_reply.xml',
        'data/ai_invoice_coworker.xml',
        'data/identity_templates.xml',
        'data/cron_monthly_summary.xml',
        'data/cron_bifrost_sync.xml',
        'data/cron_burn_rate.xml',
        'data/cron_kaizen.xml',
        'data/cron_onboard.xml',
        'data/cron_memory_consolidation.xml',
        'data/cron_scheduled_quests.xml',
        'data/cron_workspace_distill.xml',
        'data/cron_website_rag.xml',
        'data/cron_heartbeat.xml',
        'data/orchestration_skill.xml',
        'data/bridge_config.xml',
        'data/youtube_tools.xml',
        'data/browser_tools.xml',
        'data/graph_base.xml',
        'views/hr_department_views.xml',
        'views/ai_orchestration_dashboard.xml',
        'views/ai_lineage_views.xml',
        'views/ai_monthly_summary_views.xml',
        'views/ai_personal_goal_views.xml',
        'views/ai_provider_views.xml',
        'views/ai_model_views.xml',
        'views/ai_coworker_buzz_agent_wizard_views.xml',
        'views/server_action_wizard_views.xml',
        'views/ai_coworker_views.xml',
        'views/ai_coworker_hitl_views.xml',
        'views/ai_agent_views.xml',
        'views/ai_identity_views.xml',
        'views/ai_skill_views.xml',
        'views/ai_tool_views.xml',
        'views/ai_tag_views.xml',
        'views/ai_coworker_init_type_views.xml',
        'views/ai_personal_memory_views.xml',
        'views/ai_company_memory_views.xml',
        'views/ai_company_memory_category_views.xml',
        'views/ai_graph_node_views.xml',
        'views/res_company_views.xml',
        'views/res_company_memory_views.xml',
        'data/company_memory_categories.xml',
        'views/res_users_personal_memory_views.xml',
        'views/powerbox_templates.xml',
        'views/ai_session_views.xml',
        'views/workspace_activity_views.xml',
        'views/workspace_para_views.xml',
        'views/ai_coworker_error_views.xml',
        'views/mail_test_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/templates.xml',
        'views/ai_org_goal_views.xml',
        'views/ai_org_task_views.xml',
        'views/ai_org_review_views.xml',
        'views/ai_org_board_views.xml',
        'views/ai_onboarding_views.xml',
        'views/ai_onboarding_wizard_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_department_views.xml',
        'views/hr_job_views.xml',
        'data/cron_workspace_gap.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ai_agent_core/static/src/js/powerbox.js',
            'ai_agent_core/static/src/js/user_menu_ai_chat.js',
            'ai_agent_core/static/src/css/powerbox.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'demo': [
        'demo/demo_data.xml',
    ],
    'post_init_hook': 'post_init_hook_personal_memory',
    'pre_init_hook': 'pre_init_hook_check_conflicts',
}
