# -*- coding: utf-8 -*-
from . import ir_ui_view
from . import ir_action_act_window
from . import ai_provider
from . import ai_model
from . import ai_tag
from . import ai_coworker
from . import ai_coworker_buzz_agent_wizard
from . import ai_agent
from . import ai_session
from . import ai_coworker_error
from . import ai_mail_test_wizard
from . import ai_memory
from . import ai_tool
from . import ai_tool_capability
from . import ai_coworker_skill
from . import ai_identity
from . import ai_skill
from . import ai_session_line
from . import ai_coworker_init_type
from . import ai_coworker_hitl
from . import res_users
from . import res_config_settings
from . import ai_kaizen
from . import ai_tag
from . import ai_onboard
from . import base_model
from . import ai_memory_mixin
from . import ai_memory_scope
from . import ai_personal_memory
from . import ai_company_memory
from . import ai_company_memory_category
from . import res_company
from . import mail_thread
from . import mail_message
from . import discuss_channel
from . import ai_graph_node
from . import ai_personal_goal
from . import ai_company_identity
from . import ai_discuss_learning
from . import ai_org_goal
from . import ai_org_key_result
from . import ai_org_task
from . import ai_org_review
from . import ai_org_board
from . import ai_org_template
from . import ai_org_bridge
from . import ai_lineage
from . import ai_onboarding
from . import hr_employee
from . import hr_department
from . import hr_job
from . import ai_artifact_type
from . import ai_okf_concept
from . import ai_access_resolver
from . import okf_access_cache
from . import ai_okf_dashboard
from . import ai_okf_upload
from . import ir_attachment

from . import workspace_para
from . import executive_summary
from . import workspace_activity
