# -*- coding: utf-8 -*-
"""Distill layer — L2 executive summary / L3 synopsis.

Progressive summarization (task 4.2):
  L0 raw material (mail.eml, joplin.note, source records)
    → L1 concept (ai.okf.concept)
    → L2 executive summary (executive.summary.interface, level=L2)
    → L3 synopsis (executive.summary.interface, level=L3)

L2/L3 rows are ADD-only per concept level (versioned), generated by
cron/nightly distillation (task 4.3) and by PARA project close
("lessons learned", task 4.4).
"""

import logging

from odoo import models, fields, api, _

_logger = logging.getLogger(__name__)


class ExecutiveSummaryInterface(models.Model):
    """A distillation row for one concept at a given level (L2/L3)."""

    _name = 'executive.summary.interface'
    _description = 'Executive Summary (L2/L3)'
    _order = 'concept_id, level, version desc'
    _rec_name = 'title'

    concept_id = fields.Many2one(
        'ai.okf.concept', string='Concept', required=True,
        ondelete='cascade',
        help='The L1 concept this summary distills.')
    level = fields.Selection([
        ('L2', 'L2 Executive Summary'),
        ('L3', 'L3 Synopsis'),
    ], string='Level', required=True, default='L2',
        help='L2 = executive summary (2-5 sentences of business value); '
             'L3 = one-line synopsis for quick scanning.')
    version = fields.Integer('Version', default=1,
        help='ADD-only: each new distillation adds a version row.')
    title = fields.Char('Title')
    summary = fields.Text(
        string='Summary',
        help='The distilled text. L2 is a short executive summary; L3 is a '
             'one-line synopsis.')
    generated_by = fields.Char(
        'Generated By', default='cron',
        help='"cron" | "nightly" | "project_close" | coworker name')
    generated_at = fields.Datetime('Generated At', default=fields.Datetime.now)
    source_concept_id = fields.Many2one(
        'ai.okf.concept', string='Source Concept',
        help='If this row is a "lessons learned" knowledge concept produced '
             'from a project close, points at the generated knowledge concept.')

    @api.model
    def _add(self, concept, level, summary, title=None, generated_by='cron'):
        """Add a new distillation row (ADD-only versioning)."""
        self.ensure_one()
        return self.create({
            'concept_id': concept.id,
            'level': level,
            'title': title or concept.title,
            'summary': summary,
            'generated_by': generated_by,
        })

    @api.model
    def _latest(self, concept, level):
        """Return the latest distillation row for a concept+level."""
        return self.search([
            ('concept_id', '=', concept.id),
            ('level', '=', level),
        ], limit=1, order='version desc')


class AIOKFConceptDistill(models.Model):
    """Extends ai.okf.concept with distill helpers (delegated here so the
    ADD-only concept stays clean)."""

    _inherit = 'ai.okf.concept'

    # ── Distill accessors (computed, no writes to concept rows) ──
    l2_summary_id = fields.Many2one(
        'executive.summary.interface', string='L2 Executive Summary',
        compute='_compute_distill', store=False)
    l3_summary_id = fields.Many2one(
        'executive.summary.interface', string='L3 Synopsis',
        compute='_compute_distill', store=False)

    distill_html = fields.Html(
        string='Attribution', compute='_compute_distill_html', store=False,
        help='Rendered summary with per-line clickable source links and '
             'uncertain flags (task 4.1).')

    @api.depends('summary', 'attribution')
    def _compute_distill_html(self):
        for rec in self:
            try:
                rec.distill_html = rec.render_attribution_html()
            except Exception:
                rec.distill_html = False

    @api.depends()
    def _compute_distill(self):
        Summary = self.env['executive.summary.interface']
        for rec in self:
            rec.l2_summary_id = Summary._latest(rec, 'L2').id
            rec.l3_summary_id = Summary._latest(rec, 'L3').id

    def distill_l2_l3(self, l2=None, l3=None, generated_by='cron'):
        """Create L2/L3 distillation rows for this concept (task 4.2).

        Accepts provided summaries; when missing, builds a mechanical
        fallback from title + summary head so distillation works without
        an LLM provider in the loop.
        """
        Summary = self.env['executive.summary.interface']
        for rec in self:
            if l2 is None:
                head = (rec.summary or '').strip().split('\n')[0]
                l2 = _mechanical_l2(rec.title, head)
            if l3 is None:
                l3 = _mechanical_l3(rec.title)
            Summary._add(rec, 'L2', l2, title=rec.title,
                         generated_by=generated_by)
            Summary._add(rec, 'L3', l3, title=rec.title,
                         generated_by=generated_by)
        return True

    @api.model
    def _distill_inbox_batch(self, limit=20, generated_by='cron'):
        """Nightly/inbox distillation (task 4.3): distill concepts that have
        no L2 row yet (i.e. are new/unprocessed capture)."""
        Summary = self.env['executive.summary.interface']
        candidates = self.search([
            ('scope', '=', 'personal'),
            ('archived', '=', False),
        ], limit=limit, order='create_date asc')
        done = 0
        for concept in candidates:
            has_l2 = Summary.search_count([
                ('concept_id', '=', concept.id),
                ('level', '=', 'L2'),
            ])
            if has_l2:
                continue
            concept.distill_l2_l3(generated_by=generated_by)
            done += 1
        return done


def _mechanical_l2(title, head):
    """Mechanical L2 fallback (no LLM needed): one business-value sentence."""
    return f"{title or 'Koncept'}: {head[:200]}" if head else title or ''


def _mechanical_l3(title):
    """Mechanical L3 fallback: one line."""
    return title or ''
