# -*- coding: utf-8 -*-
"""Distill layer — L2 executive summary / L3 synopsis.

Progressive summarization (task 4.2):
  L0 raw material (mail.eml, joplin.note, source records)
    → L1 concept (ai.okf.concept)
    → L2 executive summary (executive.summary.interface, level=L2)
    → L3 synopsis (executive.summary.interface, level=L3)

L2/L3 rows are ADD-only per concept level (versioned), generated by
cron/nightly distillation (task 4.3) and by PARA project close
("lessons learned", task 4.4).
"""

import logging

from odoo import models, fields, api, _

_logger = logging.getLogger(__name__)


class ExecutiveSummaryInterface(models.Model):
    """A distillation row for one concept at a given level (L2/L3)."""

    _name = 'executive.summary.interface'
    _description = 'Executive Summary (L2/L3)'
    _order = 'concept_id, level, version desc'
    _rec_name = 'title'

    concept_id = fields.Many2one(
        'ai.okf.concept', string='Concept', required=True,
        ondelete='cascade',
        help='The L1 concept this summary distills.')
    level = fields.Selection([
        ('L2', 'L2 Executive Summary'),
        ('L3', 'L3 Synopsis'),
    ], string='Level', required=True, default='L2',
        help='L2 = executive summary (2-5 sentences of business value); '
             'L3 = one-line synopsis for quick scanning.')
    version = fields.Integer('Version', default=1,
        help='ADD-only: each new distillation adds a version row.')
    title = fields.Char('Title')
    summary = fields.Text(
        string='Summary',
        help='The distilled text. L2 is a short executive summary; L3 is a '
             'one-line synopsis.')
    generated_by = fields.Char(
        'Generated By', default='cron',
        help='"cron" | "nightly" | "project_close" | coworker name')
    generated_at = fields.Datetime('Generated At', default=fields.Datetime.now)
    source_concept_id = fields.Many2one(
        'ai.okf.concept', string='Source Concept',
        help='If this row is a "lessons learned" knowledge concept produced '
             'from a project close, points at the generated knowledge concept.')

    @api.model
    def _add(self, concept, level, summary, title=None, generated_by='cron',
             source_concept_id=None):
        """Add a new distillation row (ADD-only versioning).

        Model-level helper: it is called as ``env['executive.summary
        .interface']._add(...)``, which is a *legitimately empty*
        recordset (``_ids == ()``). Do NOT call ``self.ensure_one()``
        here — that is exactly what broke the nightly distillation cron
        ("Expected singleton: executive.summary.interface()",
        server action #2848). ``create()`` on an empty recordset is the
        normal Odoo idiom and works fine.
        """
        concept.ensure_one()
        summary = (summary or '').strip() or (title or concept.title or '')
        vals = {
            'concept_id': concept.id,
            'level': level,
            'title': title or concept.title,
            'summary': summary,
            'generated_by': generated_by,
        }
        if source_concept_id:
            vals['source_concept_id'] = source_concept_id.id \
                if hasattr(source_concept_id, 'id') else source_concept_id
        return self.create(vals)

    @api.model
    def _latest(self, concept, level):
        """Return the latest distillation row for a concept+level."""
        return self.search([
            ('concept_id', '=', concept.id),
            ('level', '=', level),
        ], limit=1, order='version desc')


class AIOKFConceptDistill(models.Model):
    """Extends ai.okf.concept with distill helpers (delegated here so the
    ADD-only concept stays clean)."""

    _inherit = 'ai.okf.concept'

    # ── Distill accessors (computed, no writes to concept rows) ──
    l2_summary_id = fields.Many2one(
        'executive.summary.interface', string='L2 Executive Summary',
        compute='_compute_distill', store=False)
    l3_summary_id = fields.Many2one(
        'executive.summary.interface', string='L3 Synopsis',
        compute='_compute_distill', store=False)

    distill_html = fields.Html(
        string='Attribution', compute='_compute_distill_html', store=False,
        help='Rendered summary with per-line clickable source links and '
             'uncertain flags (task 4.1).')

    @api.depends('summary', 'attribution')
    def _compute_distill_html(self):
        for rec in self:
            try:
                rec.distill_html = rec.render_attribution_html()
            except Exception:
                rec.distill_html = False

    @api.depends()
    def _compute_distill(self):
        Summary = self.env['executive.summary.interface']
        for rec in self:
            rec.l2_summary_id = Summary._latest(rec, 'L2').id
            rec.l3_summary_id = Summary._latest(rec, 'L3').id

    def distill_l2_l3(self, l2=None, l3=None, generated_by='cron'):
        """Create L2/L3 distillation rows for this concept (task 4.2).

        Accepts provided summaries; when missing, builds a mechanical
        fallback from title + summary head so distillation works without
        an LLM provider in the loop.

        NOTE: the caller-supplied ``l2``/``l3`` are only used for a
        *single* concept. They are resolved into local variables per
        record — never assigned back to the arguments — so iterating a
        multi-record recordset cannot leak the first concept's summary
        into every subsequent one.
        """
        Summary = self.env['executive.summary.interface']
        for rec in self:
            rec_l2 = l2
            rec_l3 = l3
            if rec_l2 is None:
                head = (rec.summary or '').strip().split('\n')[0]
                rec_l2 = _mechanical_l2(rec.title, head)
            if rec_l3 is None:
                rec_l3 = _mechanical_l3(rec.title)
            Summary._add(rec, 'L2', rec_l2, title=rec.title,
                         generated_by=generated_by)
            Summary._add(rec, 'L3', rec_l3, title=rec.title,
                         generated_by=generated_by)
        return True

    @api.model
    def _distill_inbox_batch(self, limit=20, generated_by='cron'):
        """Nightly/inbox distillation (task 4.3): distill concepts that have
        no L2 row yet (i.e. are new/unprocessed capture).

        Per-concept errors are logged and skipped so one malformed
        concept can never abort the whole batch (which would leave the
        cron permanently red).
        """
        Summary = self.env['executive.summary.interface']
        candidates = self.search([
            ('scope', '=', 'personal'),
            ('archived', '=', False),
        ], limit=limit, order='create_date asc')
        done = 0
        failed = 0
        for concept in candidates:
            has_l2 = Summary.search_count([
                ('concept_id', '=', concept.id),
                ('level', '=', 'L2'),
            ])
            if has_l2:
                continue
            try:
                with self.env.cr.savepoint():
                    concept.distill_l2_l3(generated_by=generated_by)
                done += 1
            except Exception:
                failed += 1
                _logger.exception(
                    'Distillation failed for concept %s (%r) — skipped',
                    concept.id, concept.title)
        if failed:
            _logger.warning(
                'Distillation batch: %s distilled, %s failed (skipped)',
                done, failed)
        return done


def _mechanical_l2(title, head):
    """Mechanical L2 fallback (no LLM needed): one business-value sentence.

    Always returns a non-empty str so the Text field never gets None/''.
    """
    title = (title or '').strip()
    head = (head or '').strip()
    if title and head:
        return f"{title}: {head[:200]}"
    return title or head[:200] or 'Koncept'


def _mechanical_l3(title):
    """Mechanical L3 fallback: one line (never None/'')."""
    return (title or '').strip() or 'Sammanfattning'
